config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  devise_for :users
  resources :homes, only: :index
  resources :users, only: [:index, :show]
  resources :games, only: [:index, :show, :new, :create, :destroy] do
    get 'pending_games', on: :collection
    post 'approve'
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :email, presence: true
  validates :username, presence: true, length: { maximum: 20 }

  belongs_to :character

  def games
    Game.where("player_1_id = ? OR player_2_id = ?", id, id)
  end

  def confirmed_games
    g = Game.where(p2_confirmation: true)
    g.where("player_1_id = ? OR player_2_id = ?", id, id)
  end

  def games_won
    games_won = []
    confirmed_games.each do |game|
      if game.winner == self
        games_won << game
      end
    end
    games_won
  end

  def rivals
    player_games = confirmed_games
    lost_games = []
    rivals = {}
    player_games.each do |game|
      if game.loser == self
        lost_games << game
      end
    end
    lost_games.each do |game|
      if rivals.has_key?(game.winner.username)
        rivals[game.winner.username] += 1
      else
        rivals[game.winner.username] = 1
      end
    end
    if rivals == {}
      rivals = { "n/a" => 0 }
    else
      rivals = rivals.sort{ |a, b| b[1] <=> a[1] }
    end
  end

  def opponents
    player_games = confirmed_games
    opponents = []
    player_games.each do |game|
      if game.player_1 == self && !opponents.include?(game.player_2.username)
        opponents << game.player_2.username
      elsif game.player_2 == self && !opponents.include?(game.player_1.username)
        opponents << game.player_1.username
      end
    end
    opponents
  end

  def wins_against(user)
    player_games = confirmed_games
    wins = 0
    player_games.each do |game|
      if game.loser.username == user
        wins += 1
      end
    end
    wins
  end

  def losses_against(user)
    player_games = confirmed_games
    losses = 0
    player_games.each do |game|
      if game.winner.username == user
        losses += 1
      end
    end
    losses
  end

  def wins_and_losses
    players = opponents
    win_loss = []
    players.each do |user|
      wins = wins_against(user)
      losses = losses_against(user)
      win_loss << [user, wins, losses]
      win_loss = win_loss.sort { |a, b| b[2] <=> a[2] }
    end
    win_loss
  end

  def nemesis
    if rivals == { "n/a" => 0 }
      ["Undefeated!", 0]
    else
      rivals.sort{ |a, b| b[1] <=> a[1] }.first
    end
  end

  def played_with(character)
    played_with_chara = []
    confirmed_games.each do |game|
      if game.player_1 == self
        if game.player_1_character == character
          played_with_chara << game
        end
      elsif game.player_2 == self
        if game.player_2_character == character
          played_with_chara << game
        end
      end
    end
    played_with_chara
  end

  def most_played_characters
    characters = Character.all
    top_4 = {}
    characters.each do |character|
      play_count = played_with(character).length
      if top_4.length < 4
        top_4[character] = play_count
      else
        top_4 = top_4.sort { |a, b| b[1] <=> a[1] }
        if play_count > top_4[3][1]
          top_4.pop
          top_4 << [character, play_count]
        end
        top_4 = top_4.sort { |a, b| b[1] <=> a[1] }
      end
    end
    top_4
  end

  def won_with(character)
    won_with_chara = []
    games_won.each do |game|
      if game.player_1 == self
        if game.player_1_character == character
          won_with_chara << game
        end
      elsif game.player_2 == self
        if game.player_2_character == character
          won_with_chara << game
        end
      end
    end
    won_with_chara
  end

  def best_character
    characters = Character.all
    best_character = Character.find_by(name: "Fox")
    chara_wins = 0
    characters.each do |character|
      if won_with(character).length > chara_wins
        chara_wins = won_with(character).length
        best_character = character
      end
    end
    best_character
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    rank_adjust
    @users = User.order(rank: :asc, wins: :desc, losses: :asc)
  end

  def show
    @user = User.find(params[:id])
    @games = @user.games
    @best_character = @user.best_character
    @wins_with_best = @user.won_with(@best_character).length
    respond_to do |format|
      format.html
      format.json do
        wins_and_losses = @user.wins_and_losses
        opponent_names = []
        wins_against = []
        losses_against = []
        most_played = []
        wins_with = []
        most_played_names = []
        wins_and_losses.each do |player|
          opponent_names << player[0]
          wins_against << player[1]
          losses_against << -player[2]
        end
        @user.most_played_characters.each do |chara|
          most_played << chara[0]
        end
        most_played.each do |chara|
          most_played_names << chara.name
          wins_with << @user.won_with(chara).length
        end
        render json: [opponent_names,
                      wins_against,
                      losses_against,
                      most_played_names,
                      wins_with
                     ]
      end
    end
  end

  protected

  def rank_adjust
    users = User.order(wins: :desc, losses: :asc)
    users.each_with_index do |user, index|
      user.rank = index + 1
      user.save
    end
  end
end

app/views/users/_account_settings.html.erb
<div class="row content text-center">
  <button data-remote="true" class="round button button-edit-form">Account Settings</button>
  <div class="hide editform">
    <div class="account-box">
      <div class="account-settings panel clearfix">
        <%= form_for(@user, url: registration_path(@user), html: { method: :put }, class: "settings-form") do |f| %>
          <fieldset>
            <legend>Account Settings</legend>

            <div>
              <div class="large-6 columns">
                <div class="field">
                  <%= f.label :crew_tag %><br />
                  <%= f.text_field :crew_tag %>
                </div>
              </div>
              <div class="large-6 columns">
                <div class="field">
                  <%= f.label :username %>
                  <i>(20 characters maximum)</i><br />
                  <%= f.text_field :username %>
                </div>
              </div>
              <div class="large-6 columns">
                <div class="field">
                  <%= f.label :email, "New Email Address" %><br />
                  <%= f.email_field :email, autofocus: true %>
                </div>
              </div>
              <div class="large-6 columns">
                <div class="field">
                  <%= f.label :character_id, "Your Main"%><br />
                  <%= f.collection_select :character_id, Character.all, :id, :name %>
                </div>
              </div>
            </div>

            <div>
              <div class="large-6 columns">
                <div class="field">
                  <%= f.label :password, "New password" %>
                  <% if @minimum_password_length %>
                  <em>(<%= @minimum_password_length %> characters minimum)</em>
                  <% end %><br />
                  <%= f.password_field :password, autocomplete: "off" %>
                </div>
              </div>
              <div class="large-6 columns">
                <div class="field">
                  <%= f.label :password_confirmation, "Confirm password change" %><br />
                  <%= f.password_field :password_confirmation, autocomplete: "off" %>
                </div>
              </div>
            </div>

            <div class="field">
              <%= f.label :current_password %> <i>** we need your current password to confirm your changes **</i>
              <%= f.password_field :current_password, autocomplete: "off" %>
            </div>

            <div class="field">
              <label>My profile photo</label>
              <%= image_tag(@user.avatar, class:"user-profile") if @user.avatar %>
              <%= f.url_field :avatar %>
            </div>

            <div class="actions">
              <ul class="right button-group round even-2 large-4 medium-8 small-12 columns">
                <li><%= link_to "Back", :back, class: "small secondary button" %></li>
                <li><%= f.submit "Update", class: "small button" %></li>
              </ul>
            </div>
          </fieldset>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
  <div class="panel text-center large-7 small-centered large-centered columns radius">
    <% if current_user && current_user.games.where(player_2_id: current_user.id, p2_confirmation: false).length != 0 %>
      <%= link_to "You have games to approve!", pending_games_games_path %>
    <% end %>
    <div class="row">
      <%= image_tag("/SmashLadderLogo.png", class: "user-profile") %>
    </div>
    <table id="leaderboard">
        <td>
          Rank
        </td>
        <td>
          Smasher
        </td>
        <td>
          Wins
        </td>
        <td>
          Losses
        </td>
      <% @users.each do |user| %>
        <tr id="<%= user.id %>">
          <td class="rank">
            <%= user.rank %>
          </td>
          <td class="username">
            <% if user.crew_tag != nil %>
              <%= user.crew_tag %>
              <%= link_to user.username, user_path(user) %>
            <% else %>
              <%= link_to user.username, user_path(user) %>
            <% end %>
          </td>
          <td class="wins">
            <%= user.wins %>
          </td>
          <td class="losses">
            <%= user.losses %>
          </td>
        </tr>
      <% end %>
    </table>
    <%= image_tag("/BarkleyQuote.png") %>
  </div>

app/views/users/show.html.erb
<div class="section-box text-center panel large-7 medium-10 small-12
large-centered medium-centered small-centered columns">
  <%= image_tag(@user.avatar, class: "user-profile") %>
  <h1 class="section-title">
    <% if @user.crew_tag != nil %>
      <%= @user.crew_tag %> <%= @user.username %>
    <% else %>
      <%= @user.username %></h1>
    <% end %>
  <h3 class="section-title"><%= @user.email %></h3>
  <% if current_user == @user %>
    <%= render 'account_settings' %>
  <% end %>

</div>
<table class="panel small-12 medium-10 large-7 small-centered large-centered columns">
  <tr>
    <td>
      Wins
    </td>
    <td>
      Losses
    </td>
    <% if @user.character %>
      <td>
        Main
      </td>
    <% end %>
  </tr>
  <tr>
    <td>
      <%= @user.wins %>
    </td>
    <td>
      <%= @user.losses %>
    </td>
    <% if @user.character %>
      <td>
        <%= image_tag @user.character.icon %>
      </td>
    <% end %>
  </tr>
</table>

<div class="panel text-center radius small-12 medium-10 large-7 small-centered large-centered columns">
  <div class="row content text-center">
    <button data-remote="true" class="round button button-charts">Player Records</button>
    <div class="hide-height charts">
      <div id="rivals" style="width:100%; height:250px;"></div>
      <div id="charawins" style="width:100%; height:250px;"></div>
    </div>
  </div>
  <div class="row"></div>
  <h3>Nemesis: <%= @user.nemesis[0] %> with <%= @user.nemesis[1] %> losses.</h3>
  <h3>Best Character: <%= @best_character.name %> with <%= @wins_with_best %> wins.</h3>
  <table>
      <h1>
        Games:
      </h1>
      <td>
        Player 1
      </td>
      <td>
        Player 2
      </td>
      <% @games.each do |game| %>
        <tr id="<%= game.id %>">
          <td class="p1">
            <% if game.winner.id == game.player_1_id %>
            <%= link_to "#{User.find(game.player_1_id).username} (W)", user_path(game.player_1) %>
            <% else %>
            <%= link_to "#{User.find(game.player_1_id).username} (L)", user_path(game.player_1) %>
            <% end %>
          </td>
          <td class="p2">
            <% if game.winner.id == game.player_2_id %>
            <%= link_to "#{User.find(game.player_2_id).username} (W)", user_path(game.player_2) %>
            <% else %>
            <%= link_to "#{User.find(game.player_2_id).username} (L)", user_path(game.player_2) %>
            <% end %>
          </td>
          <td>
            <%= link_to "Details", game_path(game) %>
          </td>
        </tr>
      <% end %>
  </table>
</div>