config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  devise_for :users
  resources :homes, only: :index
  resources :users, only: [:index, :show]
  resources :games, only: [:index, :show, :new, :create, :destroy] do
    get 'pending_games', on: :collection
    post 'approve'
  end
end

app/models/game.rb
class Game < ActiveRecord::Base
  STOCK = [4, 3, 2, 1, 0]

  belongs_to :stage
  validates :player_1_id, presence: true
  validates :player_2_id, presence: true
  validates :player_1_character_id, presence: true
  validates :player_2_character_id, presence: true
  validates :player_1_stock, presence: true
  validates :player_2_stock, presence: true
  validates :stage_id, presence: true
  validates :description, length: { maximum: 500 }

  def has_winner_and_loser?
    if player_1_stock == 0 && player_2_stock == 0
      errors.add(:game, "must have a winner")
      return false
    elsif player_1_stock > 0 && player_2_stock > 0
      errors.add(:game, "must have a loser")
      return false
    else
      return true
    end
  end

  def winner
    if player_1_stock < player_2_stock
      User.find(player_2_id)
    elsif player_1_stock > player_2_stock
      User.find(player_1_id)
    else
      User.first
    end
  end

  def loser
    if player_1_stock < player_2_stock
      User.find(player_1_id)
    elsif player_1_stock > player_2_stock
      User.find(player_2_id)
    else
      User.first
    end
  end

  def players
    p1 = User.find(player_1_id)
    p2 = User.find(player_2_id)
    "#{p1.username} vs. #{p2.username}"
  end

  def player_1
    User.find(player_1_id)
  end

  def player_1_character
    Character.find(player_1_character_id)
  end

  def player_2
    User.find(player_2_id)
  end

  def player_2_character
    Character.find(player_2_character_id)
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.all.where(p2_confirmation: true).reverse
  end

  def show
    @game = Game.find(params[:id])
  end

  def new
    if signed_in?
      @game = Game.new
      @users = User.where.not(id: current_user.id)
      @stages = Stage.all
    else
      authenticate_user!
    end
  end

  def create
    @game = Game.new(game_params)
    @game.player_1_id = current_user.id
    @users = User.where.not(id: current_user.id)
    @stages = Stage.all
    if @game.has_winner_and_loser?
      if @game.save
        flash[:success] = "Game saved!"
        redirect_to games_path
      else
        flash[:alert] = @game.errors.full_messages.join(", ")
        render :new
      end
    else
      flash[:alert] = "Game must have a winner and loser!"
      render :new
    end
  end

  def pending_games
    @games = current_user.games.where(p2_confirmation: false).reverse
  end

  def approve
    @game = Game.find(params[:game_id])
    if current_user == @game.player_2
      @game.p2_confirmation = true
      @game.save
      p1 = User.find(@game.player_1_id)
      p2 = current_user
      if @game.winner == p1
        p1.wins += 1
        p2.losses += 1
      else
        p1.losses += 1
        p2.wins += 1
      end
      p1.save
      p2.save
      rank_adjust
      flash[:success] = "Game Approved!"
    end
    redirect_to pending_games_games_path
  end

  def destroy
    @game = Game.find(params[:id])
    if signed_in? && (current_user == @game.player_2 || current_user == @game.player_1)
      unless @game.p2_confirmation == true
        @game.destroy
        rank_adjust
        flash[:success] = 'Game deleted successfully!'
        redirect_to users_path
      end
    elsif !signed_in?
      authenticate_user!
    else
      flash[:alert] = "Stop trying to delete things that aren't yours!"
      redirect_to game_path(@game)
    end
  end

  protected

  def game_params
    params.require(:game).permit(
      :player_2_id,
      :player_1_character_id,
      :player_2_character_id,
      :player_1_stock,
      :player_2_stock,
      :stage_id,
      :description
      )
  end

  def rank_adjust
    users = User.order(wins: :desc, losses: :asc)
    users.each_with_index do |user, index|
      user.rank = index + 1
      user.save
    end
  end
end

app/views/games/_form.html.erb
<%= form_for @game do |f| %>
  <%= f.label :player_2_id, "Player 2" %>
  <%= f.collection_select :player_2_id, @users, :id, :username, prompt: true %>
  <br>
  <%= f.label :player_1_character_id, "Your Character" %>
  <%= f.collection_select :player_1_character_id, Character.all, :id, :name %>
  <br>
  <%= f.label :player_2_character_id, "Player 2's Character" %>
  <%= f.collection_select :player_2_character_id, Character.all, :id, :name %>
  <br>
  <%= f.label :player_1_stock, "Your Remaining Stock" %>
  <%= f.collection_select :player_1_stock, Game::STOCK, :to_i, :to_s %>
  <br>
  <%= f.label :player_2_stock, "P2 Remaining Stock" %>
  <%= f.collection_select :player_2_stock, Game::STOCK, :to_i, :to_s %>
  <br>
  <%= f.label :stage_id, "Stage" %>
  <%= f.collection_select :stage_id, @stages, :id, :name %>
  <br>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <br>
  <%= f.submit "Submit", class: "button small round expand success" %>
<% end %>

app/views/games/index.html.erb
<div class="panel small-12 medium-10 large-7 small-centered large-centered columns">
  <table>
      <h1>
        Games:
      </h1>
      <td>
        Player 1
      </td>
      <td>
        Player 2
      </td>
    <% @games.each do |game| %>
      <tr id="<%= game.id %>">
        <td class="p1">
          <% if game.winner.id == game.player_1_id %>
          <%= link_to "#{User.find(game.player_1_id).username} (W)", user_path(game.player_1) %>
          <% else %>
          <%= link_to "#{User.find(game.player_1_id).username} (L)", user_path(game.player_1) %>
          <% end %>
        </td>
        <td class="p2">
          <% if game.winner.id == game.player_2_id %>
          <%= link_to "#{User.find(game.player_2_id).username} (W)", user_path(game.player_2) %>
          <% else %>
          <%= link_to "#{User.find(game.player_2_id).username} (L)", user_path(game.player_2) %>
          <% end %>
        </td>
        <td>
          <%= link_to "Details", game_path(game) %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/games/new.html.erb
<div class="panel small-8 medium-6 large-5 large-centered medium-centered small-centered columns">
  <h1 class="text-center">Submit Your Game!</h1>

  <%= render 'form' %>
</div>

app/views/games/pending_games.html.erb
<div class="panel small-12 medium-10 large-7 small-centered large-centered columns">
  <table>
      <h1>
        Pending Approval:
      </h1>
      <% if @games.length == 0 %>
        <td>
          No games are pending! Go play more!
        </td>
      <% else %>
        <td>
          Player 1
        </td>
        <td>
          Player 2
        </td>
      <% end %>
    <% @games.each do |game| %>
      <tr id="<%= game.id %>">
        <td class="p1">
          <% if game.winner.id == game.player_1_id %>
          <%= link_to "#{User.find(game.player_1_id).username} (W)", user_path(game.player_1) %>
          <% else %>
          <%= link_to "#{User.find(game.player_1_id).username} (L)", user_path(game.player_1) %>
          <% end %>
        </td>
        <td class="p2">
          <% if game.winner.id == game.player_2_id %>
          <%= link_to "#{User.find(game.player_2_id).username} (W)", user_path(game.player_2) %>
          <% else %>
          <%= link_to "#{User.find(game.player_2_id).username} (L)", user_path(game.player_2) %>
          <% end %>
        </td>
        <td>
          <%= link_to "Details", game_path(game) %>
          <% if game.player_2 == current_user %>
            <%= button_to "Approve this!", game_approve_path(game), class: "button tiny"%>
          <% else %>
            (Waiting on your opponent's approval)
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/games/show.html.erb
<div class="section-box text-center panel large-7 medium-10 small-12
large-centered medium-centered small-centered columns">
  <%= image_tag @game.player_1.avatar, class: "thumbnail" %>
  <%= @game.players %>
  <%= image_tag @game.player_2.avatar, class: "thumbnail" %>
  <% if @game.player_2 == current_user && @game.p2_confirmation == false %>
    <%= button_to "Approve this!", game_approve_path(@game), class: "button small"%>
  <% end %>
  <% if @game.player_1 == current_user && @game.p2_confirmation == false || @game.player_2 == current_user && @game.p2_confirmation == false %>
    <%= button_to "Delete this?", @game, method: :delete, class: "button tiny alert" %>
  <% end %>
  </div>
  <table class="panel small-12 medium-10 large-7 small-centered large-centered columns">
    <tr>
      <td>
        Players:
      </td>
      <td>
        <%= @game.player_1.crew_tag %> <%= link_to @game.player_1.username, user_path(@game.player_1) %>
      </td>
      <td>
        <%= @game.player_2.crew_tag %> <%= link_to @game.player_2.username, user_path(@game.player_2) %>
      </td>
    </tr>
    <tr>
      <td>
        Characters:
      </td>
      <td>
        <%= @game.player_1_character.name %>
      </td>
      <td>
        <%= @game.player_2_character.name %>
      </td>
    </tr>
    <tr>
      <td>
        Stock Remaining:
      </td>
      <td>
        <% @game.player_1_stock.times do %>
          <%= image_tag @game.player_1_character.icon %>
        <% end %>
      </td>
      <td>
        <% @game.player_2_stock.times do %>
          <%= image_tag @game.player_2_character.icon %>
        <% end %>
      </td>
    </tr>
    <tr>
      <td>
        Stage:
      </td>
      <td>
        <%= @game.stage.name %>
      </td>
      <td>
        <%= image_tag @game.stage.icon %>
      </td>
    </tr>
  </table>
<% unless @game.description == "" %>
  <div class="panel small-12 medium-10 large-7 small-centered large-centered columns">
      Description:
      <%= @game.description %>
  </div>
<% end %>