config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  devise_for :users
  resources :homes, only: :index
  resources :users, only: [:index, :show]
  resources :games, only: [:index, :show, :new, :create, :destroy] do
    get 'pending_games', on: :collection
    post 'approve'
  end
end

app/views/layouts/_topbar.html.erb
<div class="fixed">
  <nav class="top-bar" data-topbar>
    <ul class="title-area">
      <li class="name">
        <div class="logo-wrapper">
          <a class="logo" href="/users"><img src="/SmashLadderLogoTopbar.png" /></a>
        </div>
          </li>
          <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
        </ul>
    <section class="top-bar-section">
      <ul class="right">
        <li><%= link_to "Leaderboard", users_path %></li>
        <li class="has-dropdown">
          <a href="#">Games</a>
          <ul class="dropdown">
            <% if current_user %>
              <li><%= link_to "Add a Game", new_game_path %></li>
              <li><%= link_to "Your Pending Games", pending_games_games_path %></li>
            <% end %>
            <li><%= link_to "All Games", games_path %></li>
          </ul>
        </li>
        <%- if current_user -%>
          <li><%= link_to "My Profile", user_path(current_user) %></li>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <%- else -%>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
        <%- end -%>
      </ul>
    </section>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link rel="shortcut icon" href="/favicon.ico" />
  <title>SmashLadder</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%- flash.each do |key, value| -%>
    <div class="large-12 alert-box <%= key %>">
      <%= value %>
    </div>
  <%- end -%>

  <%= render "layouts/topbar" %>
  <%= yield %>

  <%= javascript_include_tag 'application' %>
  <%= yield :extra_footer %>
</body>
</html>